package hse.dto

import game.backgammon.response.HistoryResponseItem
import game.backgammon.response.HistoryResponseItemType

class AcceptDoubleHistoryResponseItem : HistoryResponseItem(HistoryResponseItemType.ACCEPT_DOUBLE)